### ISSUE TITLE
Error with Octane 

### ISSUE THREAD

**Issue by ytalo202** [open-southeners/laravel-vapor-response-compression#1]
I implemented this library in project. all work very well,but when i wanted to use "Octane" i had many error with Auth functions.
Do you have some tips to me?

**Comment by d8vjork** [comment]
We were using this with Octane since then, no issues

Not sure this issue is related to this package specifically as this package doesn't touch any of the authorization

**Comment by d8vjork** [comment]
I'll close this as it might be related but feel free to reply adding more details if you still think otherwise
