### ISSUE TITLE
Exclude binary responses

### ISSUE THREAD

**Issue by travisghansen** [open-southeners/laravel-vapor-response-compression#2]
Should this use a similar check as found here: https://github.com/pop-culture-studio/laravel-vapor-gzip/blob/main/src/GzipResponse.php#L51

I suspect this is for avoiding file download endpoints and/or responses that were possibly already compressed.

**Comment by d8vjork** [comment]
Nice one! Might add something like this

**Comment by travisghansen** [comment]
I've seen some variations of these compression middleware which check for the existence of the response `Content-Encoding` header as well. I think doing both the check in the link and the header check would be sane.

**Comment by d8vjork** [comment]
Maybe as a variation on the one you sent adding another check for `Symfony\Component\HttpFoundation\StreamedResponse` for the ones using `response()->streamDownload()`

I'll add them + tests

**Comment by d8vjork** [comment]
@travisghansen You can check on 0c74ea48cca5b04e4b8521c3ace7ec657d808541

Release in progress 👍

**Comment by travisghansen** [comment]
I like it!
